# Generated by Django 4.2.14 on 2024-07-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('todoUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todoUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
